baseURL: https://nickanderegg.github.io/static-conversations-demo/
title: Static Conversations Demo

author: Nick Anderegg

params:
  description: A demo site for Static Conversations comments.
  copyright: "Nick Anderegg. This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

languageCode: en-us

# menu:
#   main:
#     identifier: about
#     name: about
#     url: "/about/"
#     weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

