name: parse comments from issues

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - closed
      - reopened
  issue_comment:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
    paths:
      - '.github/process-comments.yml'
  workflow_dispatch:

jobs:
  process-comments:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout the repository locally
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install the Static Conversations tool
        run: |
          sudo apt-get install python3.9
          gh release download -R NickAnderegg/static-conversations --pattern '*.whl'
          python3.9 -m pip install ./static_conversations*.whl

      - name: Load comments
        run: convo load

      - name: Commit updated comment files
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git add ./data
          git commit -m "[AUTOMATED] update blog comments"

          git push origin main
